[package]
name = "base32"
version = "0.1.1"
authors = [ "Andreas Ots <qrpth@qrpth.eu>", "Valerii Hiora" ]

[lib]
name = "base32"

[dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
